### ISSUE TITLE
Add an FAQ explaining 'rdisk' for slightly less technical users

### ISSUE THREAD

**Issue by aaronmergerequest** [rentzsch/stressdrive#19]
I would have submitted this via the more normal GIT channels but I think this needs editing for accuracy and clarity. Basically, I don't think the concept of "rdisk" is known widely enough to not to confuse some users of this software. 

You might consider adding something along these lines to the FAQ section:

**When I list my disks I do not see "rdiskX", I only see "diskX"**

When you access a disk on your system via "diskX" the OS manages the reads and writes which can include the use of buffers as well as other data management techniques that could cause certain sectors to be used more than others.

Unix systems also allow "raw" access to write data directly to the disk using the format "rdiskX". stressdrive requires raw access to ensure full and controlled reads and writes to the storage modules on SSDs. 

Once you've identified the top-level (physical, not synthesized) drive identifier 'diskX' simply add an 'r' for use by the app. For example, if your `diskutil list` shows /dev/disk4 as your target, use /dev/rdisk4 in your command.

**Comment by rentzsch** [comment]
Sure. Do you want me to copy+paste in your FAQ entry, or do you want to do it?

**Comment by rentzsch** [comment]
Github makes it easy, just [go here](https://github.com/rentzsch/stressdrive/blob/develop/README.markdown) and hit the pencil icon in the upper right hand corner. But I can do it as well.

**Comment by aaronmergerequest** [comment]
Thanks for the reply. I'm happy to add it. My concern was that my addition was _conceptually_ correct but not _technically_ correct. If you'd like me to add this I'll have to do a little more research to double-check my assertions first.

**Comment by aaronmergerequest** [comment]
Ok, I've massaged the FAQ a little and posted the proposed change. After some expansion and contraction, I nearly ended up where I started, so I guess the first draft wasn't too bad after all. Haha.

**Comment by rentzsch** [comment]
Thanks. Where do you post the proposed change?

**Comment by aaronmergerequest** [comment]
I had followed your link above and while there was a pencil icon, it didn't seem to take my changes so I created a fork. You can see the addition here: https://github.com/aaronmergerequest/stressdrive/tree/patch-1?tab=readme-ov-file#when-i-list-my-disks-i-do-not-see-rdiskx-i-only-see-diskx.

Sorry if this is a bit of a pain, I don't work with github much.

**Comment by rentzsch** [comment]
That's weird, [GitHub should have](https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository) forked my repository to one that you control, with [your edit](https://github.com/aaronmergerequest/stressdrive/commit/649571703ab3fb6f21f241f638f4274ea31ad3bd).

For some reason, a Pull Request was never created, so just [created one myself](https://github.com/rentzsch/stressdrive/pull/20) and merged it.

**Comment by aaronmergerequest** [comment]
Sounds good!
