### ISSUE TITLE
Checkpoint checks

### ISSUE THREAD

**Issue by lkraider** [rentzsch/stressdrive#7]
For large drives, determining the full checksum can take several hours (ie: 40h in my external 4Tb drive).

It would be nice to set an interval for checking integrity at every X Gb, where X is a command line option, so that problems can be identified earlier even if overall time might increase.

**Comment by rentzsch** [comment]
This would definitely identify certain types of hardware failure more quickly. Here are the tradeoffs I see:
- I assume the implementation would be a generate-write-read-verify cycle for current random data block. This, however, would fit in various caches. So it won't necessarily test end-to-end functionality, you'd still need the final lengthy verification phase to know for sure. But as a fail-fast it's fine.
- As mentioned, would slow down overall operation.
- Would add more complication to the code. But probably not that much.

I see this more useful for HDDs than SSDs. SSDs are great at covering up such errors.

Overall, I'd be willing to accept a Pull Request that implements this. Ideally behind an opt-in command line flag.
